I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\meganschmid\\OneDrive - Microsoft\\Desktop\\Game Jam\\fhl24\\Fortunes Finest Code\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\meganschmid\Downloads\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\meganschmid\Downloads\renpy-8.2.1-sdk\renpy\main.py", line 582, in main
    renpy.dump.dump(False)
  File "C:\Users\meganschmid\Downloads\renpy-8.2.1-sdk\renpy\dump.py", line 260, in dump
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\meganschmid\\OneDrive - Microsoft\\Desktop\\Game Jam\\fhl24\\Fortunes Finest Code\\game\\saves\\navigation.json'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Fortune's Finest 1.0
Thu Apr 18 08:23:54 2024
